comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
coverage:
  status:
    project:
      default:
        target: "100"
    patch:
      default:
        target: "100"
