name: Benchmark
on:
  push:
    branches:
      - main

jobs:
  benchmark:
    name: Check performance regeression.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          clean: true

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Run benchmark with nox
        run: nox -s benchmark

      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Pytest-Benchmark Benchmark
          tool: 'pytest'
          output-file-path: benchmark-output.json
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '130%'
          comment-on-alert: true
          fail-on-alert: true
