name: Benchmark
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  benchmark:
    name: Check performance regeression.
    runs-on: ubuntu-latest
    permissions:
      # deployments permission to deploy GitHub pages website
      deployments: write
      # contents permission to update benchmark contents in gh-pages branch
      contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@266a5d6a507c6927766a67b8380f323eacd977a2 # tav=v1.4
        with:
          egress-policy: block
          disable-telemetry: true
          allowed-endpoints: >
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443

      - name: Checkout main branch
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
        with:
          clean: true

      - name: Setup Python
        uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # tag=v4
        with:
          python-version: "3.9"

      - name: "Install dev dependencies"
        run: |
          pip install nox
          pip install nox-poetry
          pip install poetry

      - name: Run benchmark with nox
        run: nox -s benchmark

      - name: Store benchmark result in github.io
        uses: benchmark-action/github-action-benchmark@3b3014adac5e456db8ad428ccc01bec75242487f # tag=v1
        with:
          name: Pytest-Benchmark Benchmark
          tool: 'pytest'
          output-file-path: benchmark-output.json
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '130%'
          comment-on-alert: true
          fail-on-alert: true
