name: Benchmark
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  benchmark:
    name: Check performance regeression.
    runs-on: ubuntu-latest
    permissions:
      # deployments permission to deploy GitHub pages website
      deployments: write
      # contents permission to update benchmark contents in gh-pages branch
      contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # tav=v1.4
        with:
          egress-policy: audit
          disable-telemetry: false
          allowed-endpoints: >
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443
            api.github.com:443

      - name: Checkout main branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          clean: true

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.13"

      - name: "Install dev dependencies"
        run: |
          pip install nox==2022.11.21
          pip install poetry==1.3.1
          pip install nox-poetry==1.0.2

      - name: Run benchmark with nox
        run: nox -s benchmark

      - name: Store benchmark result in github.io
        uses: benchmark-action/github-action-benchmark@4de1bed97a47495fc4c5404952da0499e31f5c29 # tag=v1
        with:
          name: Pytest-Benchmark Benchmark
          tool: 'pytest'
          output-file-path: benchmark-output.json
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '130%'
          comment-on-alert: true
          fail-on-alert: true
