# .github/workflows/detect-secrets.yaml
name: detect-secrets
on: [pull_request]

permissions:
  contents: read

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@266a5d6a507c6927766a67b8380f323eacd977a2
      with:
        egress-policy: audit
        disable-telemetry: false
        # allowed-endpoints: >
        #   detect-secrets-client-version.s3.us-south.cloud-object-storage.appdomain.cloud:443
        #   github.com:443

    - name: Checkout
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      with:
        fetch-depth: 0

    # - name: Run IBM's detect-secrets
    #   uses: tomwillis608/detect-secrets-action@5358d1f7c812225e42dc7b235c512e07a7ec58e4 # tag=v2.1.1

    - name: Setup Python
      uses: actions/setup-python@5ccb29d8773c3f3f653e1705f474dfaa8a06a912 # v4
      with:
        python-version: "3.7"

    - name: "Install dev dependencies"
      run: |
        pip install --upgrade pip
        pip install --use-pep517 --upgrade "git+https://github.com/ibm/detect-secrets.git@master#egg=detect-secrets"
        pip install --no-cache-dir certifi>=2022.12.7 --upgrade

    - name: "Run detect-secrets"
      run: |
        set -o pipefail
        set -exu
        DS_REQUIRE_BASELINE=0
        DS_BASELINE_FILE="./.secrets.baseline"
        ls -lta
        detect-secrets scan >"$DS_BASELINE_FILE"
        if [ ! -r "$DS_BASELINE_FILE" ]; then
          if [ "$DS_REQUIRE_BASELINE" -eq 0 ]; then
            detect-secrets scan >"$DS_BASELINE_FILE"
          else
            echo "No readable detect-secrets baseline file found at '$DS_BASELINE_FILE', and it was set to required by \$DS_REQUIRE_BASELINE ($DS_REQUIRE_BASELINE)"
            exit 255
          fi
        fi
