# .github/workflows/detect-secrets.yaml
name: detect-secrets
on: [pull_request]

permissions:
  contents: read

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@e680f76da57a1e1ce6dc3eed69efc703fcca8dce
      with:
        egress-policy: block
        disable-telemetry: true
        allowed-endpoints: >
          detect-secrets-client-version.s3.us-south.cloud-object-storage.appdomain.cloud:443
          github.com:443

    - name: Checkout
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      with:
        fetch-depth: 0

    - name: Run IBM's detect-secrets
      uses: tomwillis608/detect-secrets-action@aeaa7205d35551e4ef6092d604143ed6372fc92c # tag=master
