# .github/workflows/detect-secrets.yaml
name: detect-secrets
on: [pull_request]

permissions:
  contents: read

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Checkout
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      with:
        fetch-depth: 0

    - name: Run IBM's detect-secrets
      uses: tomwillis608/detect-secrets-action@aeaa7205d35551e4ef6092d604143ed6372fc92c # tag=master
