# .github/workflows/detect-secrets.yaml
name: detect-secrets
on: [pull_request]

permissions:
  contents: read

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8e0b4153524c217e5dce81df0986478e95a7004a
      with:
        egress-policy: block
        disable-telemetry: true
        allowed-endpoints: >
          detect-secrets-client-version.s3.us-south.cloud-object-storage.appdomain.cloud:443
          files.pythonhosted.org:443
          github.com:443
          pypi.org:443

    - name: Checkout
      uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4
      with:
        python-version: "3.7"

    - name: "Install dev dependencies"
      run: |
        pip install --upgrade pip
        pip install --use-pep517 --upgrade "git+https://github.com/ibm/detect-secrets.git@master#egg=detect-secrets"
        pip install --no-cache-dir certifi>=2022.12.7 --upgrade
        sudo apt-get install -y jq

    - name: "Run detect-secrets"
      run: |
        set -o pipefail
        set -exu
        DS_REQUIRE_BASELINE=1
        DS_BASELINE_FILE="./.secrets.baseline"
        detect-secrets --version
        if [ ! -r "$DS_BASELINE_FILE" ]; then
          if [ "$DS_REQUIRE_BASELINE" -eq 0 ]; then
            detect-secrets -v scan >"$DS_BASELINE_FILE"
          else
            echo "No readable detect-secrets baseline file found at '$DS_BASELINE_FILE', and it was set to required by \$DS_REQUIRE_BASELINE ($DS_REQUIRE_BASELINE)"
            exit 255
          fi
        else
          cp .secrets.baseline .secrets.new
          detect-secrets scan --update .secrets.new
          # if there is any difference between the known and newly detected secrets, break the build
          list_secrets() { jq -r '.results | keys[] as $key | "\($key),\(.[$key] | .[] | .hashed_secret)"' "$1" | sort; }
          if ! diff <(list_secrets .secrets.baseline) <(list_secrets .secrets.new) >&2; then
            echo "Detected new secrets in the repo" >&2
            exit 1
          fi
        fi
