# .github/workflows/detect-secrets.yaml
name: detect-secrets
on: [pull_request]

permissions:
  contents: read

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@3888ae1b9fbce718b86218b974255090596e99cd
      with:
        egress-policy: block
        disable-telemetry: true
        allowed-endpoints: >
          detect-secrets-client-version.s3.us-south.cloud-object-storage.appdomain.cloud:443
          github.com:443

    - name: Checkout
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      with:
        fetch-depth: 0

    - name: Run IBM's detect-secrets
      uses: tomwillis608/detect-secrets-action@aeaa7205d35551e4ef6092d604143ed6372fc92c # tag=master
