# .github/workflows/detect-secrets.yaml
name: detect-secrets
on: [pull_request]

permissions:
  contents: read

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@266a5d6a507c6927766a67b8380f323eacd977a2
      with:
        egress-policy: block
        disable-telemetry: true
        allowed-endpoints: >
          detect-secrets-client-version.s3.us-south.cloud-object-storage.appdomain.cloud:443
          github.com:443

    - name: Checkout
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      with:
        fetch-depth: 0

    - name: Run IBM's detect-secrets
      uses: sett-and-hive/detect-secrets-action@5358d1f7c812225e42dc7b235c512e07a7ec58e4 # tag=v2.1.1

