# .github/workflows/tests.yml
name: Tests
on: push

permissions:
  contents: read

jobs:
  tests:
    name: "Python $({ matrix.python-version }) tests"
    runs-on: ubuntu-latest
    env:
      USING_COVERAGE: '3.9'
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813 # tag=v1.4
      with:
        egress-policy: audit
        disable-telemetry: false
        # egress-policy: block
        # disable-telemetry: true
        # allowed-endpoints: >
        #   auth.docker.io:443
        #   codecov.io:443
        #   files.pythonhosted.org:443
        #   github.com:443
        #   production.cloudflare.docker.com:443
        #   pypi.org:443
        #   raw.githubusercontent.com:443
        #   registry-1.docker.io:443
        #   storage.googleapis.com:443
        #   uploader.codecov.io:443

    - name: "Checkout"
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      with:
        clean: true

    - name: "Python setup"
      uses: actions/setup-python@152ba7c4dd6521b8e9c93f72d362ce03bf6c4f20 # tag=v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - run: pip install nox==2022.8.7
    - run: pip install poetry==1.2.0
    - run: pip install nox-poetry==1.0.1

    - run: nox -p ${{ matrix.python-version }}

    - name: "Post to codecov.io"
      if: "contains(env.USING_COVERAGE, matrix.python-version)"
      uses: codecov/codecov-action@81cd2dc8148241f03f5839d295e000b8f761e378 # tag=v3
      with:
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
