# .github/workflows/tests.yml
name: Tests
on: push
jobs:
  tests:
    name: "Python $({ matrix.python-version }) tests"
    runs-on: ubuntu-latest
    env:
      USING_COVERAGE: '3.8'
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        clean: true

    - name: "Set up Python"
      uses: actions/setup-python@v3
      with:
        python-version: "${{ matrix.python-version }}"

    - name: "Install dependencies"
      run: |
        pip install nox
        pip install nox-poetry
        pip install poetry

    - name: "Run nox for ${{ matrix.python-version }}"
      run: nox

    - name: "Post to codecov.io"
      if: "contains(env.USING_COVERAGE, matrix.python-version)"
      uses: codecov/codecov-action@v3
      with:
        verbose: true
        fail_ci_if_error: true
