# .github/workflows/tests.yml
name: Tests
on: push

permissions:
  contents: read

jobs:
  tests:
    name: "Python $({ matrix.python-version }) tests"
    runs-on: ubuntu-latest
    env:
      USING_COVERAGE: '3.8'
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813 # tag=v1.4
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: "Checkout"
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      with:
        clean: true

    - name: "Set up Python"
      uses: actions/setup-python@d09bd5e6005b175076f227b13d9730d56e9dcfcb # tag=v4
      with:
        python-version: "${{ matrix.python-version }}"

    - name: "Install dependencies"
      run: |
        pip install nox
        pip install nox-poetry
        pip install poetry

    - name: "Run nox for ${{ matrix.python-version }}"
      run: nox

    - name: "Post to codecov.io"
      if: "contains(env.USING_COVERAGE, matrix.python-version)"
      uses: codecov/codecov-action@81cd2dc8148241f03f5839d295e000b8f761e378 # tag=v3
      with:
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
