# .github/workflows/tests.yml
name: Tests

on:
  push:
    branches:
      - '*'
      - '!gh-pages'
      # Run on all branches except gh-pages
  pull_request:
    branches:
      - '*'
      - '!gh-pages'
      # Run on all branches except gh-pages

permissions:
  contents: read

jobs:
  tests:
    name: "Python $({ matrix.python-version }) tests"
    runs-on: ubuntu-latest
    env:
      USING_COVERAGE: '3.9'
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813 # tag=v1.4
      with:
        egress-policy: block
        allowed-endpoints: >
          auth.docker.io:443
          codecov.io:443
          files.pythonhosted.org:443
          github.com:443
          production.cloudflare.docker.com:443
          pypi.org:443
          pyup.io:443
          registry-1.docker.io:443
          storage.googleapis.com:443
          uploader.codecov.io:443

    - name: "Checkout"
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      with:
        clean: true

    - name: "Python setup"
      uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - run: pip install nox==2022.11.21
    - run: pip install poetry==1.3.1
    - run: pip install nox-poetry==1.0.2

    - run: nox -p ${{ matrix.python-version }}

    - name: "Post to codecov.io"
      if: "contains(env.USING_COVERAGE, matrix.python-version)"
      uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3
      with:
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
