# .github/workflows/tests.yml
name: Tests
on: push

permissions:
  contents: read

jobs:
  tests:
    name: "Python $({ matrix.python-version }) tests"
    runs-on: ubuntu-latest
    env:
      USING_COVERAGE: '3.9'
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8a1ef77ccd7a6d18b009c8cd833b00f49386b657 # tag=v1.4
      with:
        egress-policy: block
        allowed-endpoints: >
          auth.docker.io:443
          codecov.io:443
          files.pythonhosted.org:443
          github.com:443
          production.cloudflare.docker.com:443
          pypi.org:443
          pyup.io:443
          registry-1.docker.io:443
          storage.googleapis.com:443
          uploader.codecov.io:443

    - name: "Checkout"
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      with:
        clean: true

    - name: "Python setup"
      uses: actions/setup-python@5ccb29d8773c3f3f653e1705f474dfaa8a06a912 # v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - run: pip install nox==2022.11.21
    - run: pip install poetry==1.3.1
    - run: pip install nox-poetry==1.0.2

    - run: nox -p ${{ matrix.python-version }}

    - name: "Post to codecov.io"
      if: "contains(env.USING_COVERAGE, matrix.python-version)"
      uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # tag=v3
      with:
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
